### ISSUE TITLE
Error while running (can't parse uri:druby://172.16.2.203)

### ISSUE THREAD

**Issue by dsbanerjee90** [christopherwharrop/rocoto#80] opened 2020-10-07 14:00 UTC
I am getting following error while running rocoto with 
rocotorun -w <test.xml> -d < database >

can't parse uri:druby://172.16.2.203:44288
Workflow Manager Initialization failed.
ERROR! Could not launch database server process.

Could you please help how to tackle this issue.

Thanks in advance!

**Comment by christopherwharrop-noaa** [comment] 2020-10-07 14:49
Thank you for reporting this problem.  An initial look at it indicates it may be caused by a character encoding problem. I am looking into it.

**Comment by christopherwharrop-noaa** [comment] 2020-10-07 15:47
@dsbanerjee90 - Which version of Ruby are you using?

**Comment by dsbanerjee90** [comment] 2020-10-07 15:48
It is ruby-2.7.2

**Comment by christopherwharrop-noaa** [comment] 2020-10-07 23:04
@dsbanerjee90 - I don't know how to reproduce your error, but I've tried adding some encoding of the URI that is written across a pipe between two processes to see if it helps.  Can you try checking out the [feature/uri-encode](https://github.com/christopherwharrop/rocoto/tree/feature/uri-encode) branch to see whether it makes a difference?

**Comment by dsbanerjee90** [comment] 2020-10-08 09:22
@christopherwharrop-noaa I used the modified script that you did for rocoto/sbin/rocotodbserver and rocoto/lib/workflowmgr/launchserver.rb but it seems the same error persists. Its also showing two new warning messages but I assume this is probably due to the use of {} in the script which this version of ruby (2.7.2) don't like. I got something like this --

rocoto/sbin/rocotodbserver:50: warning: Using the last argument as keyword parameters is deprecated
rocoto/sbin/rocotodbserver:51: warning: Using the last argument as keyword parameters is deprecated
rocoto/lib/workflowmgr/launchserver.rb:61: warning: Using the last argument as keyword parameters is deprecated
rocoto/lib/workflowmgr/launchserver.rb:62: warning: Using the last argument as keyword parameters is deprecated
run.xml.rocoto.exp :: can't parse uri:druby://172.16.0.1:42711
run.xml.rocoto.exp :: Workflow Manager Initialization failed.
run.xml.rocoto.exp :: ERROR! Could not launch database server process.

I have also tried with ruby-2.6.6 but the error is seemingly the same.

Let me send you the log during the time of compilation. There are several warning messages which might be helpful to have a solution.
Thanks a lot.
[compile.rocoto.log](https://github.com/christopherwharrop/rocoto/files/5346677/compile.rocoto.log)

**Comment by christopherwharrop-noaa** [comment] 2020-10-08 14:10
@dsbanerjee90  - I'm going to try installing your version of Ruby to see if that allows me to reproduce your issue.

**Comment by christopherwharrop** [comment] 2020-11-24 17:09
@dsbanerjee90 - I'm sorry this has taken so long to get back to you.  I've just pushed a fix that will probably address your issue.  Please checkout the develop branch, run ./INSTALL, and try it.

**Comment by dsbanerjee90** [comment] 2020-11-26 20:10
Hi Chris! Thanks a lot for your immense help. It is working perfectly fine now. I am so happy :) Hope to meet you sometime in future so I can thank you in person. Thanks a lot again! Cheers!

**Comment by dsbanerjee90** [comment] 2020-11-26 20:10
> Hi Chris! Thanks a lot for your immense help. It is working perfectly fine now. I am so happy :) Hope to meet you sometime in future so I can thank you in person. Thanks a lot again! Cheers!

You can close this issue thread.

**Closed as completed** 2023-07-11 22:08 UTC
